<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<title>我们的时光</title>
<link rel="stylesheet" media="screen" href="css/todos.css" />
<link rel="stylesheet" media="screen" href="./css/bootstrap.min.css"></link>
<link rel="stylesheet" media="screen" href="./css/bootstrap-responsive.css">
<link rel="stylesheet" media="screen" href="./css/page.css"></link>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="#">时光</a>
				<div class="nav-collapse collapse">
					<p class="navbar-text pull-right">
						Logged in as <a href="#" class="navbar-link">Username</a>
					</p>
					<ul class="nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
					</ul>
				</div>

				<!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span3">
				<div class="well sidebar-nav">
					<ul class="nav nav-list">
						<li class="nav-header">Sidebar</li>
						<li class="active"><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li class="nav-header">Sidebar</li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li class="nav-header">Sidebar</li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
						<li><a href="#">Link</a></li>
					</ul>
				</div>
				<!--/.well -->
			</div>
			<!--/span-->
			<div class="span9">
				<div id="todoapp" >
					<div>
						<input id="new-todo" type="input" placeholder="开始记录你的时光">
					</div>

					<div id="main">
						<ul id="todo-list"></ul>
					</div>
					
					<div id="instructions">美好的时光.</div>
				</div>
			</div>
			<!--/span-->
		</div>
		<!--/row-->
		
		<footer>
			<p>&copy; Company 2012</p>
		</footer>
	</div>
	<!--/.fluid-container-->


	<script src="lib/json2.js"></script>
	<script src="lib/jquery.min.js"></script>
	<script src="lib/underscore.js"></script>
	<script src="lib/backbone.js"></script>
	<script src="lib/localstorage.js"></script>
	<script src="js/todos.js"></script>

	<!-- Templates -->

	<script type="text/template" id="item-template">
    <div class="view">
    	<div>  
			<h2><%- title %></h2>
		</div>
	    <span class="label"><%- body %> </span>
	    <span class="label"><%- user_id %> </span>
	    <span class="label"><%- mtime %> </span>
        <a class="destroy"></a>
    </div>
    <input class="edit" type="text" value="<%- title %>" />
   </script>

	<script id="jiji-view-users" type="text/html">
			<div class="side-inner">
				<ul class="nav nav-tabs nav-stacked affix">
					<li>
						<a href="#dropdowns" class="member-search-wrapper">
							<input type="text" name="username" placeholder="搜索用户" class="search"></input>
						</a>
					</li>
					<% _.each(users, function(user) {%>
						<li>
							<a href="#user/<%=user.user_name%>"><%= user.view_name %></a>
						</li>
					<%});%>
				</ul>
			</div>
		</script>
</body>
</html>