<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" media="screen" href="css/times.css" />
</head>
<body>
<div class="feedList">
	<ul>
		<li type="3">
			<div class="headPic">
				<a target="_blank" href="#" title="美食"><span></span></a> 
				<img alt="" src="http://tp1.sinaimg.cn/2904211072/180/5639902699/0"> 
				<a target="_blank" class="icon_tag" href="#">美食</a>
			</div>
			<div class="feedCon">
				<span class="feedListCor"></span>
				<span class="feedTagName"><a target="_blank" href="#"><span>美食</span></a></span>
				<div class="feedFrom">
					<a target="_blank" href="#">Ivanyule</a>
					<span class="editby">采编自</span>
					<a target="_blank" href="#" id="author_13_49d0ba6333000919_92930">jodie</a>
					<a target="_blank" class="feedDate" href="#" style="display: none;">昨天 12:28</a>
				</div>
				
				<div class="feedTitle">饺子的7种包法，过年时准用的上~</div>
				
				<div id="feedText_13_49d0ba6333000919_92930" class="feedText">
					<div class="longtext_prv" id="small_13_49d0ba6333000919_92930">
						<div>
							<span id="small_13_49d0ba6333000919_92930long" class="long_pic">
							&nbsp;做饭很简单：给自己扫盲，备份个~饺子的7种包法，过年用得上哟， 零基础学做饭。。。&nbsp;&nbsp;图片分享字：做饭很简单
							</span>
						</div>
					</div>
					<div style="display: none;" class="longtext_all" id="big_13_49d0ba6333000919_92930">
						<div class="packup">
							<a action-type="hideLongArticle" action-data="type=13&amp;blogid=49d0ba6333000919&amp;blogtype=3&amp;uid=1238415971&amp;mid=&amp;rnd=92930&amp;isReprint=0&amp;from=qing"
								href="javascript:void(0)">收起全文</a>
						</div>
					</div>
				</div>
				<div class="feedAttr">
					<div class="tags">
						<div class="tagWrap">
							<span class="tagTit"></span>
							<span class="tagCon">
								<span style="left: -1px; -moz-user-select: none;" class="tagList">
									<a title="美食" href="http://qing.weibo.com/tag/%E7%BE%8E%E9%A3%9F" target="_blank">美食</a>
									<a title="生活" href="http://qing.weibo.com/tag/%E7%94%9F%E6%B4%BB" target="_blank">生活</a>
									<a title="心情" href="http://qing.weibo.com/tag/%E5%BF%83%E6%83%85" target="_blank">心情</a>
									<a title="摄影" href="http://qing.weibo.com/tag/%E6%91%84%E5%BD%B1" target="_blank">摄影</a>
								</span>
							</span>
						</div>
					</div>
					<a href="javascript:void(0)" onclick="xDB &amp;&amp; xDB.showReprint('49d0ba6333000919_92930', 0, this );return false;" from="qing" class="feedAttr_transfer">转载<em>(37)</em></a>
					<a onclick="xDB &amp;&amp; xDB.showComment('49d0ba6333000919_92930', '1238415971', this, '49d0ba6333000919');return false;" blog_id="49d0ba6333000919" href="javascript:void(0)" from="qing" class="feedAttr_commend">评论<em>(44)</em></a>
					<span class="loveBox">
					   <span>
					       <a href="#" onclick="xDB.like &amp;&amp; xDB.like('49d0ba6333000919_92930',this,'1238415971','49d0ba6333000919');return false;" class="love" from="qing" title="喜欢">喜欢<em>(39)</em></a>
					   </span>
					</span>
				</div>
				<!-- 转载 -->
				<div style="display: none;" id="reprint_13_49d0ba6333000919_92930">
					<div class="feedTransfer">
						<div class="input">
							<textarea
								style="font-family: 'Microsoft Yahei'; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; word-wrap: break-word; font-size: 13px; line-height: 19px;"
								id="reprintInput_13_49d0ba6333000919_92930"></textarea>
							<div class="syncToWB">
								<a class="ys" target="_blank" href="http://qing.weibo.com/setting.html?show=sync">同步到新浪微博</a>
							</div>
							<!--同步到新浪微博 end-->
							<a class="btn" onclick="xDB &amp;&amp; xDB.reprint('49d0ba6333000919_92930', '1238415971', '49d0ba6333000919');return false;" href="javascript:void(0)"><span>转载</span></a><em class="green"
								id="reprintInput_13_49d0ba6333000919_92930_lengthinf">你还可以输入<em>140</em>个字
							</em>
						</div>
					</div>
				</div>
				<!-- 评论 -->
				<div style="display: none;" id="comment_13_49d0ba6333000919_92930">
					<div class="comment">
						<div class="input">
							<textarea id="replyInput_13_49d0ba6333000919_92930"></textarea>
							<a onclick="xDB &amp;&amp; xDB.reply('49d0ba6333000919_92930',this);return false;" href="javascript:void(0)" blog_id="49d0ba6333000919" from="qing" class="btn"><span>评论</span></a><em
								class="green" id="replyInput_13_49d0ba6333000919_92930_lengthinf"></em>
						</div>
						<div style="display: none;" class="rowLine"></div>
						<ul class="commentList" id="commentList_13_49d0ba6333000919_92930"></ul>
					</div>
				</div>
			</div>
		</li>
	</ul>
	</div>
</body>
</html>